# Generated by Django 5.1.4 on 2024-12-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cert_id", models.CharField(max_length=255, unique=True)),
                ("issuer", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("status", models.CharField(default="valid", max_length=50)),
                ("revoke_reason", models.TextField(blank=True, null=True)),
                ("revoke_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
