# Generated by Django 5.1.4 on 2024-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ca_server", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="certificate",
            old_name="revoke_date",
            new_name="date_issued",
        ),
        migrations.RenameField(
            model_name="certificate",
            old_name="subject",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="cert_id",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="revoke_reason",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="valid_from",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="valid_to",
        ),
        migrations.AddField(
            model_name="certificate",
            name="csr",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="certificate",
            name="expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="issuer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
